timezone: US/Mountain
outline:
  outline_dir: outline/book{book_num}/
  primary_outline_file: book{book_num}-scenes.md
  outline_name: book{book_num}-{{outline_type}}.md
convert:
  metadata_path:
    default: skeleton/book{book_num}-metadata.txt
    shunn-docx: skeleton/book{book_num}-metadata-docx.txt
  frontmatter_files:
    - skeleton/Book {book_num} Copyright.md
    - skeleton/Book {book_num} Dedication.md
  backmatter_files: []
  css:
    # css_dir: path/to/css/
    manuscript_pdf_css_path: "pdf-light.css"
    misc_pdf_css_path: "pdf-misc.css"
    epub_css_path: "epub.css"
  # markdown_template_dir: path/to/templates/
  shunn_repo_url: https://github.com/escapewindow/pandoc-templates
  shunn_repo_path: null
find_files_by_name_cmd: ["fd", "-s", "-F"]
find_files_by_content_cmd: ["rg", "-F", "-l"]
